module.exports = `
  type User {
    _id: ID,
    username: String,
    email: String,
    isActivated: Boolean
  }

  extend type Mutation {
    changePassword(oldPassword: String!, newPassword: String!): String @secure
  }
`
